# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='date',
            new_name='posted_on',
        ),
    ]
