# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20161202_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='gmailid',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
    ]
