# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20161208_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
