# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20161209_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_id', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=1000)),
                ('vendor_type', models.CharField(max_length=1000)),
                ('vendor_mobileno', models.CharField(max_length=1000)),
            ],
        ),
    ]
