# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('noOfFlats', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('secratoryName', models.CharField(max_length=100)),
            ],
        ),
    ]
